

default_platform(:android)

# upload to internal test to Google Play
lane :internal do 
  # build the app bundle if you haven't already 
  gradle(task: 'bundleRelease')
  # Upload to internal test
  upload_to_play_store(
    track: 'internal',
    aab: '../build/app/outputs/bundle/release/app-release.aab', # Update this path if your AAB is generated in a different location
    skip_upload_apk: true,
    skip_upload_images: true,
    skip_upload_screenshots: true,
    skip_upload_metadata: true,
    skip_upload_changelogs: true,
    skip_upload_aab: false,
  )
end

# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end

#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
  
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
